### ISSUE TITLE
Problem dragging newly added Nestable Item

### ISSUE THREAD

**Issue by paulm17** [rhwilr/vue-nestable#1]
Hi,

Many thanks for building this.

I need to add items to the tree, but I keep on getting an error when I try to move a newly created tree.

I have created an example to demonstrate the problem.

https://codesandbox.io/s/8lq00np3ql

Add an item and then try to drag it.

The error I get is: Uncaught TypeError: Cannot read property 'length' of undefined

The error pertains to this:  https://github.com/rhwilr/vue-nestable/blob/f33acf4d4aeff2f0ab36c51eaaad6d857fe8e169/src/nestable-helpers.js#L40

Let me know if you need anything.

Thanks!

**Comment by rhwilr** [comment]
Thanks for this bug repost @paulm17 
The problem here is that the item you add does not have a `children` property.
If you pass a list of items that don't have a `children` property, vue-nestable will update the list and add that property to each item. But only on the initial render.

This is intentional, since checking each item on every render update could be a performance issue on large lists.

I just published an [update](https://github.com/rhwilr/vue-nestable/commit/84210dafc3bc7a5c9d1544015d175769f71cc1b3) that now checks if the item has a child property and only then allows you to nest an item. This means that you will no longer get an error, but you can not nest items below a newly added element unless you add a `children` property.

I might even remove the initial conversion in a future update and make it a requirement for items to have a `children` property.

**Comment by paulm17** [comment]
Thanks for pushing out the update so quickly.  Got it working now, cheers!
