### ISSUE TITLE
Collapse / Expand feature ?

### ISSUE THREAD

**Issue by jdriesen** [rhwilr/vue-nestable#4]
Hi Ralph, @rhwilr 

If I can ask ... do you plan to implement a collapse and expand functionality ?

Thanks in advance for your reply,

Kind regards,

Johnny (Belgium)

**Comment by rhwilr** [comment]
Hi Johnny

I did initially plan to implement collapse functionality and there is still some evidence of that in the codebase from the initial draft.
But currently I don‘t have the need for this feature, so I didn‘t spend any more time on it.
I intend to release 1.0 without it soon and maybe then take another look at it. But if you have the need for this feature I will happily accept a PR.

**Comment by Espumisan** [comment]
You can set collapsing seperated from this plugin

**Comment by ysk2014** [comment]
how do it?

**Comment by BernardTsai** [comment]
I am no Vue expert but I think it is possible to achieve the collapse/expand behaviour by 
a) setting the **classProp property**  of the VueNestable component (documentation I believe needs to be updated since this property is currently named 'class' there), 
b) adding a simple **event handler** in the slot template to toggle the classProp property (e.g. by adding or removing 'collapsed') and 
c) defining a corresponding **CSS rule** which hides the contents of the child elements:

```
.nestable-item.collapsed > ol  {
  display: none;
} 
```
